# airbyte-values.yaml
global:
  airbyteUrl: "https://dataflow.cedia.org.ec"
  image:
    tag: "1.7.2"
  env:
    - name: JOB_MAIN_CONTAINER_CPU_REQUEST
      value: "500m"
    - name: JOB_MAIN_CONTAINER_CPU_LIMIT
      value: "2"
    - name: JOB_MAIN_CONTAINER_MEMORY_REQUEST
      value: "1Gi"
    - name: JOB_MAIN_CONTAINER_MEMORY_LIMIT
      value: "3Gi"

server:
  env:
    - name: MAX_CHECK_WORKERS
      value: "4"
    - name: MAX_SYNC_WORKERS
      value: "4"
    - name: WORKLOAD_LAUNCHER_PARALLELISM
      value: "4"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"

workloadLauncher:
  env:
    - name: WORKLOAD_LAUNCHER_PARALLELISM
      value: "4"
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

worker:
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"

postgresql:
  primary:
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi" 
      limits:   
        cpu: "1"   
        memory: "1Gi" 
    persistence:
      size: 20Gi